SELECT
  "incident number" AS incident_number,
  "exposure number" AS exposure_number,
  id,
  address,
  "incident date" AS incident_date,
  "call number" AS call_number,
  "alarm dttm" AS alarm_dttm,
  "arrival dttm" AS arrival_dttm,
  "close dttm" AS close_dttm,
  city,
  zipcode,
  battalion,
  "station area" AS station_area,
  box,
  "suppression units" AS suppression_units,
  "suppression personnel" AS suppression_personnel,
  "ems units" AS ems_units,
  "ems personnel" AS ems_personnel,
  "other units" AS other_units,
  "other personnel" AS other_personnel,
  "first unit on scene" AS first_unit_on_scene,
  "estimated property loss" AS estimated_property_loss,
  "estimated contents loss" AS estimated_contents_loss,
  "fire fatalities" AS fire_fatalities,
  "fire injuries" AS fire_injuries,
  "civilian fatalities" AS civilian_fatalities,
  "civilian injuries" AS civilian_injuries,
  "number of alarms" AS number_of_alarms,
  "primary situation" AS primary_situation,
  "mutual aid" AS mutual_aid,
  "action taken primary" AS action_taken_primary,
  "action taken secondary" AS action_taken_secondary,
  "action taken other" AS action_taken_other,
  "detector alerted occupants" AS detector_alerted_occupants,
  "property use" AS property_use,
  "area of fire origin" AS area_of_fire_origin,
  "ignition cause" AS ignition_cause,
  "ignition factor primary" AS ignition_factor_primary,
  "ignition factor secondary" AS ignition_factor_secondary,
  "heat source" AS heat_source,
  "item first ignited" AS item_first_ignited,
  "human factors associated with ignition" AS human_factors_associated_with_ignition,
  "structure type" AS structure_type,
  "structure status" AS structure_status,
  "floor of fire origin" AS floor_of_fire_origin,
  "fire spread" AS fire_spread,
  "no flame spread" AS no_flame_spread,
  "number of floors with minimum damage" AS number_of_floors_with_minimum_damage,
  "number of floors with significant damage" AS number_of_floors_with_significant_damage,
  "number of floors with heavy damage" AS number_of_floors_with_heavy_damage,
  "number of floors with extreme damage" AS number_of_floors_with_extreme_damage,
  "detectors present" AS detectors_present,
  "detector type" AS detector_type,
  "detector operation" AS detector_operation,
  "detector effectiveness" AS detector_effectiveness,
  "detector failure reason" AS detector_failure_reason,
  "automatic extinguishing system present" AS automatic_extinguishing_system_present,
  "automatic extinguishing system type" AS automatic_extinguishing_system_type,
  "automatic extinguishing system performance" AS automatic_extinguishing_system_performance,
  "automatic extinguishing system failure reason" AS automatic_extinguishing_system_failure_reason,
  "number of sprinkler heads operating" AS number_of_sprinkler_heads_operating,
  "supervisor district" AS supervisor_district,
  neighborhood_district,
  point,
  created_at,
  updated_at
FROM {{ source('fire_incidents_staging', 'fire_incidents_staging') }}